openapi: 3.0.3
info:
  title: Simple CRM
  version: 1.0.0
  description: Project
paths:
  /companies/:
    get:
      operationId: companies_retrieve
      description: Lists all records of companies.
      summary: List companies
      tags:
      - companies
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company'
          description: ''
    post:
      operationId: companies_create
      description: Creates a company record.
      summary: Add new company
      tags:
      - companies
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Company'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Company'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Company'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company'
          description: ''
  /companies/{id}/:
    get:
      operationId: companies_retrieve_2
      description: Returns the company record with the provided pk.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - companies
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company'
          description: ''
    patch:
      operationId: companies_partial_update
      description: |-
        Partially updates the company record with the provided pk and
        returns the updated record.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - companies
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedCompany'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedCompany'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedCompany'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company'
          description: ''
    delete:
      operationId: companies_destroy
      description: |-
        Deletes the company record with the provided pk and
        returns empty body response.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - companies
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /companies/{id}/expanded/:
    get:
      operationId: companies_expanded_retrieve
      description: |-
        Returns the company record with the provided pk with additional field
        with all the employee records that are related to that company.
      summary: Company with expanded employees field
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - companies
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExpandedCompany'
          description: ''
  /employees/:
    get:
      operationId: employees_retrieve
      description: Lists all records of employees.
      tags:
      - employees
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
          description: ''
    post:
      operationId: employees_create
      description: Creates an employee record.
      tags:
      - employees
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Employee'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Employee'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Employee'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
          description: ''
  /employees/{id}/:
    get:
      operationId: employees_retrieve_2
      description: Returns the employee record with the provided pk.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - employees
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
          description: ''
    patch:
      operationId: employees_partial_update
      description: |-
        Partially updates the employee record with the provided pk and
        returns the updated employee record.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - employees
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedEmployee'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedEmployee'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedEmployee'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
          description: ''
    delete:
      operationId: employees_destroy
      description: |-
        Deletes the employee record with the provided pk and
        returns empty body response.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - employees
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
components:
  schemas:
    Company:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 64
        logo:
          type: string
          format: uri
        description:
          type: string
          maxLength: 300
      required:
      - description
      - id
      - logo
      - name
    Employee:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        first_name:
          type: string
          maxLength: 32
        last_name:
          type: string
          maxLength: 32
        date_of_birth:
          type: string
          format: date
        photo:
          type: string
          format: uri
        position:
          type: string
          maxLength: 64
        salary:
          type: string
          format: decimal
          pattern: ^-?\d{0,6}(?:\.\d{0,2})?$
        employer:
          type: integer
          nullable: true
      required:
      - date_of_birth
      - first_name
      - id
      - last_name
      - photo
      - position
      - salary
    ExpandedCompany:
      type: object
      properties:
        name:
          type: string
          maxLength: 64
        logo:
          type: string
          format: uri
        description:
          type: string
          maxLength: 300
        employees:
          type: array
          items:
            $ref: '#/components/schemas/Employee'
          readOnly: true
      required:
      - description
      - employees
      - logo
      - name
    PatchedCompany:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 64
        logo:
          type: string
          format: uri
        description:
          type: string
          maxLength: 300
    PatchedEmployee:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        first_name:
          type: string
          maxLength: 32
        last_name:
          type: string
          maxLength: 32
        date_of_birth:
          type: string
          format: date
        photo:
          type: string
          format: uri
        position:
          type: string
          maxLength: 64
        salary:
          type: string
          format: decimal
          pattern: ^-?\d{0,6}(?:\.\d{0,2})?$
        employer:
          type: integer
          nullable: true
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
